clear;close all;clc;

disp('Make sure you turned off Dropbox syncing. It will affect rmdir operation and leads to unstable results.')
disp('Type "dbcont" to proceed.')
keyboard

import matlab.unittest.TestSuite;

names = {...
    'Chan_test.m';...
    'ChanInfo_test.m';...
    'ChanInfo_test.m';...
    'ChanInfo_6OHDA_KCN_test.m';...
    'ChanSpecifier_test.m';...
    'EventChan_test.m';...
    'FileListHeaders_test.m';...
    'FileList_test.m';...
    'MarkerChan_test.m';...
    'RecordInfo_test.m';...
    'Record_test.m';...
    'WaveformChan_test.m';...
    ...
    };

n = length(names);
C = cell(1, n);
for i = 1:n
    C{i} = TestSuite.fromFile(names{i});
end

Chan_classfamily_suite = [C{:}];

result = run(Chan_classfamily_suite);

disp(result)