classdef validateSpike2dataFiles_test < matlab.unittest.TestCase
    % Parameters for validateSmrFiles_test, validateMatFiles_test
    %
    % See also
    % validateSmrFiles_test, validateMatFiles_test
    
    properties (TestParameter)
        
        type = struct(...
            'probe_SUA_mac', unipath('/Users/kouichi/Dropbox/Private_Dropbox/Kouichi MATLAB data/thalamus/probe/SUA'),...
            'probe_LFP_mac', unipath('/Users/kouichi/Dropbox/Private_Dropbox/Kouichi MATLAB data/thalamus/probe/LFP'),...
            'juxta_SUA_mac', unipath('/Users/kouichi/Dropbox/Private_Dropbox/Kouichi MATLAB data/thalamus/juxta SUA'),...
            'probe_SUA_pc',  unipath('Z:\Dropbox\Private_Dropbox\Kouichi MATLAB data\thalamus\probe\SUA'),...
            'probe_LFP_pc',  unipath('Z:\Dropbox\Private_Dropbox\Kouichi MATLAB data\thalamus\probe\LFP'),...
            'juxta_SUA_pc',  unipath('Z:\Dropbox\Private_Dropbox\Kouichi MATLAB data\thalamus\juxta SUA'));
                
        brainstate = struct('act', 'act', ...
            'actdelta', 'actdelta', ...
            'swa', 'swa')
    end
    
    properties
        formats = struct('smr', 'smr', 'mat', 'mat');
        
        expr = struct('filenames', '^kjx\d{3}([a-zA-Z]{1,2}\d{2}.*@\d{1,4}-\d{1,4}(_)?)+',...
            ...
            'chantitles_probe_smr', struct(...
                'SUA', '(^IpsiEEG$|^probe[AB][01][0-9](e$|s$|E$)|^mergeinfo$)',...
                'SUA_wf', '(^IpsiEEG$)',...
                'SUA_ev', '(^probe[AB][01][0-9](e$|s$|E$)|^mergeinfo$)',...
                'LFP', '(^IpsiEEG$|^probe[AB][01][0-9]($|h$))',...
                'LFP_wf', '(^IpsiEEG$|^probe[AB][01][0-9]($|h$))',...
                'LFP_ev', '',...
                'EEG', '(^IpsiEEG$)'),...
            ...
            'chantitles_juxta_smr', struct(... 
                'SUA', '',...
                'SUA_ev', '^unite$|^smalle$',...%TODO
                'SUA_wf', '',...
                'LFP', '^ME1_LFP$',...
                'LFP_wf', '',...
                'LFP_ev', '',... 
                'EEG', '(^IpsiEEG$)'),...
            ...
            'chantitles_probe_mat', struct(...
                'SUA', '(^IpsiEEG$|^probe[AB][01][0-9](e$|s$|E$))',...
                'SUA_wf', '(^IpsiEEG$)',...
                'SUA_ev', '(^probe[AB][01][0-9](e$|s$|E$))',...
                'SUA_ev_unique', '(^probe[AB][01][0-9](e$|s$))',...
                'LFP', '(^IpsiEEG$|^probe[AB][01][0-9]($|h$))',...
                'LFP_wf', '(^IpsiEEG$|^probe[AB][01][0-9]($|h$))',...
                'LFP_ev', '',...
                'EEG', '(^IpsiEEG$)'),...
            ...
            'chantitles_juxta_mat', struct(...
                'SUA', '(^IpsiEEG$|^unite$|^smalle$|^ME1 LFP$)',...
                'SUA_ev', '^unite$|^smalle$',...%TODO
                'SUA_wf', '',...
                'LFP', '^ME1_LFP$',...
                'LFP_wf', '',...
                'LFP_ev', '',...    
                'EEG', '(^IpsiEEG$)'),...
            ...
            'durationInFilenames', '[a-zA-Z]{1,2}\d{2}[A-Z]{0,1}@(\d{1,4})-(\d{1,4})');
        
    end
    
    
    
end